defaults:
  - model: catboost

data:
  dir: data
  file_path: ${data.dir}/cdcNormalDiabetic.csv
  target_col: Label
  downsample: false
  # feature_cols:
  #   - Age
  #   - GenHlth
  #   - BMI
  #   - HighBP
  #   - HighChol
  #   - Income
  #   - CholCheck
  #   - Sex
  #   - Education
  #   - MentHlth
  #   - PhysHlth
  #   - HvyAlcoholConsump
  #   - DiffWalk
  #   - HeartDiseaseorAttack
  #   - Smoker

train:
  max_epochs: 30
  devices: 1
  log_every_n_steps: 50
  batch_size: 64

results:
  avg_options:
    - micro
    - macro
    - weighted
    - binary
  file_path: results.csv
  prob_path: catboost_prob.csv

igtd:
  nrows: 14
  ncols: 18
  save_image_size: 3
  max_step: 30000
  val_step: 300
  fea_dist_method: "Euclidean"
  image_dist_method: "Euclidean"
  error: "abs"
  output_dir: ${data.dir}/IGTD
  img_dir: ${igtd.output_dir}/data

# Hyperparameter tuning
n_trials: 100
