name: catboost

hyperparams:
  iterations: 1000
  learning_rate: 0.02706306272232865  # 0.01
  max_depth: 9  # 10
  verbose: 0
  eval_metric: AUC
  random_seed: 42
  class_weights: [1, 3]
  subsample: 0.5566294691758115
  colsample_bylevel: 0.8686305801000598
  min_data_in_leaf: 77
  l2_leaf_reg: 9.73664580580515
  random_strength: 3.661474300115658e-05
  bagging_temperature: 0.6773337749385995
  border_count: 185
  grow_policy: SymmetricTree

hyperparams_search_space:
  learning_rate:
    low: 0.001
    high: 0.3
    log: true

  max_depth:
    low: 3
    high: 12

  subsample:
    low: 0.5
    high: 1.0

  colsample_bylevel:
    low: 0.5
    high: 1.0

  min_data_in_leaf:
    low: 5
    high: 100

  l2_leaf_reg:
    low: 1.0
    high: 10.0
    log: true

  random_strength:
    low: 1e-9
    high: 10.0
    log: true

  bagging_temperature:
    low: 0.0
    high: 1.0

  border_count:
    low: 32
    high: 255

  grow_policy:
    choices:
      - SymmetricTree
      - Depthwise
      - Lossguide
