name: catboost

# Baseline hyperparameters for tuning
# hyperparams:
#   iterations: 1000
#   learning_rate: 0.01
#   max_depth: 10
#   verbose: 0
#   random_seed: 42
#   eval_metric: AUC
#   class_weights: [1, 3]

# Original dataset x customized class weights
hyperparams:
  iterations: 1000
  verbose: 0
  random_seed: 42
  eval_metric: AUC
  class_weights: [1, 3]
  learning_rate: 0.04037990953434713
  max_depth: 3
  subsample: 0.6772374229490887
  colsample_bylevel: 0.7601245364810707
  min_data_in_leaf: 78
  l2_leaf_reg: 4.573175139753625
  random_strength: 0.07805575047630997
  bagging_temperature: 0.27292730290786615
  border_count: 242
  grow_policy: Depthwise

# Original dataset x ENN
# hyperparams:
#   iterations: 1000
#   verbose: 0
#   random_seed: 42
#   eval_metric: AUC
#   learning_rate: 0.007436739055454489
#   max_depth: 12
#   subsample: 0.6785617434718708
#   colsample_bylevel: 0.6190675255323781
#   min_data_in_leaf: 11
#   l2_leaf_reg: 2.9543576545558277
#   random_strength: 0.00048626305001355814
#   bagging_temperature: 0.7040328500253457
#   border_count: 126
#   grow_policy: Depthwise

# Dataset after feature engineering x customized class weights
# hyperparams:
#   iterations: 1000
#   verbose: 0
#   random_seed: 42
#   eval_metric: AUC
#   class_weights: [1, 3]
#   learning_rate: 0.11743651961356788
#   max_depth: 12
#   subsample: 0.6486434988314246
#   colsample_bylevel: 0.7838176376440327
#   min_data_in_leaf: 49
#   l2_leaf_reg: 4.021579333160483
#   random_strength: 1.90132481411361
#   bagging_temperature: 0.2685141247901936
#   border_count: 243
#   grow_policy: Lossguide

# Dataset after feature engineering x ENN
# hyperparams:
#   iterations: 1000
#   verbose: 0
#   random_seed: 42
#   eval_metric: AUC
#   learning_rate: 0.010489030807812456
#   max_depth: 12
#   subsample: 0.6628035815139937
#   colsample_bylevel: 0.8222313136450979
#   min_data_in_leaf: 8
#   l2_leaf_reg: 1.1758580200346394
#   random_strength: 0.00017733091929676906
#   bagging_temperature: 0.17099447601983578
#   border_count: 152
#   grow_policy: Depthwise

# 15 selected features x customized class weights
# hyperparams:
#   iterations: 1000
#   verbose: 0
#   random_seed: 42
#   eval_metric: AUC
#   class_weights: [1, 3]
#   learning_rate: 0.029433327671998657
#   max_depth: 3
#   subsample: 0.804405864487038
#   colsample_bylevel: 0.7580173868223173
#   min_data_in_leaf: 23
#   l2_leaf_reg: 7.879668961798419
#   random_strength: 0.00031498954867148455
#   bagging_temperature: 0.3352978387310267
#   border_count: 247
#   grow_policy: Lossguide

# 15 selected features x ENN
# hyperparams:
#   iterations: 1000
#   verbose: 0
#   random_seed: 42
#   eval_metric: AUC
#   learning_rate: 0.014487403956587177
#   max_depth: 12
#   subsample: 0.7761615743034963
#   colsample_bylevel: 0.7490907648119899
#   min_data_in_leaf: 24
#   l2_leaf_reg: 2.702541688882471
#   random_strength: 0.10458863026432662
#   bagging_temperature: 0.6512454805574379
#   border_count: 245
#   grow_policy: Depthwise

hyperparams_search_space:
  learning_rate:
    low: 0.001
    high: 0.3
    log: true

  max_depth:
    low: 3
    high: 12

  subsample:
    low: 0.5
    high: 1.0

  colsample_bylevel:
    low: 0.5
    high: 1.0

  min_data_in_leaf:
    low: 5
    high: 100

  l2_leaf_reg:
    low: 1.0
    high: 10.0
    log: true

  random_strength:
    low: 1e-9
    high: 10.0
    log: true

  bagging_temperature:
    low: 0.0
    high: 1.0

  border_count:
    low: 32
    high: 255

  grow_policy:
    choices:
      - SymmetricTree
      - Depthwise
      - Lossguide
